In [53]:
import pandas as pd
import numpy as np

In [54]:
# preprocessing tools
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

# New imports for detailed metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

## Load data

In [55]:
df = pd.read_csv('kidney_disease.csv')

# Short look of data
df.head()

id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd  
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd  
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd  

[5 rows x 26 columns]

# Short definitions for each important features

age: "patient age (years)",
....bp : "blood pressure (mm/hg),
...sg : "urine specific gravity",
...al : "albumum in urine"
...hemo : hemoglobin level (g/dl)
...sc : serum creatinine(mg/dl)
...htn: Hypertension (yes/no)
...dm : diabetes mellitus (yes/no)
...cad: Coronary Artery Disease (yes/no)
...appet: Patient has a good or poor appetite
...pc: Pus Cell status (normal/abnormal)
...classification: The target column with two values: ckd (Chronic Kidney Disease) and not ckd

## Initial data cleaning

In [56]:
df.drop('id', axis=1, inplace=True)
df.columns = ['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
              'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
              'appet', 'pe', 'ane', 'classification']

df['dm'] = df['dm'].replace(to_replace={'\tno': 'no', '\tyes': 'yes', ' yes': 'yes'})
df['cad'] = df['cad'].replace(to_replace='\tno', value='no')
df['classification'] = df['classification'].replace(to_replace='ckd\t', value='ckd')


In [57]:
# Missing values of the dataset

df.isnull().sum()

age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

## Encoding and Type conversion

In [58]:
df['rbc'] = df['rbc'].map({'normal': 1, 'abnormal': 0})
df['pc'] = df['pc'].map({'normal': 1, 'abnormal': 0})
df['pcc'] = df['pcc'].map({'present': 1, 'notpresent': 0})
df['ba'] = df['ba'].map({'present': 1, 'notpresent': 0})
df['htn'] = df['htn'].map({'yes': 1, 'no': 0})
df['dm'] = df['dm'].map({'yes': 1, 'no': 0})
df['cad'] = df['cad'].map({'yes': 1, 'no': 0})
df['appet'] = df['appet'].map({'good': 1, 'poor': 0})
df['pe'] = df['pe'].map({'yes': 1, 'no': 0})
df['ane'] = df['ane'].map({'yes': 1, 'no': 0})
df['classification'] = df['classification'].map({'ckd': 1, 'notckd': 0})

numeric_cols = ['age', 'bp', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df

age    bp     sg   al   su  rbc   pc  pcc   ba    bgr  ...   pcv  \
0    48.0  80.0  1.020  1.0  0.0  NaN  1.0  0.0  0.0  121.0  ...  44.0   
1     7.0  50.0  1.020  4.0  0.0  NaN  1.0  0.0  0.0    NaN  ...  38.0   
2    62.0  80.0  1.010  2.0  3.0  1.0  1.0  0.0  0.0  423.0  ...  31.0   
3    48.0  70.0  1.005  4.0  0.0  1.0  0.0  1.0  0.0  117.0  ...  32.0   
4    51.0  80.0  1.010  2.0  0.0  1.0  1.0  0.0  0.0  106.0  ...  35.0   
..    ...   ...    ...  ...  ...  ...  ...  ...  ...    ...  ...   ...   
395  55.0  80.0  1.020  0.0  0.0  1.0  1.0  0.0  0.0  140.0  ...  47.0   
396  42.0  70.0  1.025  0.0  0.0  1.0  1.0  0.0  0.0   75.0  ...  54.0   
397  12.0  80.0  1.020  0.0  0.0  1.0  1.0  0.0  0.0  100.0  ...  49.0   
398  17.0  60.0  1.025  0.0  0.0  1.0  1.0  0.0  0.0  114.0  ...  51.0   
399  58.0  80.0  1.025  0.0  0.0  1.0  1.0  0.0  0.0  131.0  ...  53.0   

         wc   rc  htn   dm  cad  appet   pe  ane  classification  
0    7800.0  5.2  1.0  1.0  0.0    1.0  0.0  0.0               1  
1    6000.0  NaN  0.0  0.0  0.0    1.0  0.0  0.0               1  
2    7500.0  NaN  0.0  1.0  0.0    0.0  0.0  1.0               1  
3    6700.0  3.9  1.0  0.0  0.0    0.0  1.0  1.0               1  
4    7300.0  4.6  0.0  0.0  0.0    1.0  0.0  0.0               1  
..      ...  ...  ...  ...  ...    ...  ...  ...             ...  
395  6700.0  4.9  0.0  0.0  0.0    1.0  0.0  0.0               0  
396  7800.0  6.2  0.0  0.0  0.0    1.0  0.0  0.0               0  
397  6600.0  5.4  0.0  0.0  0.0    1.0  0.0  0.0               0  
398  7200.0  5.9  0.0  0.0  0.0    1.0  0.0  0.0               0  
399  6800.0  6.1  0.0  0.0  0.0    1.0  0.0  0.0               0  

[400 rows x 25 columns]

## Filling the missing values

In [59]:
# Numerical -> median
# Categorical -> mode
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = df[col].fillna(df[col].mode()[0])    
    else:
        df[col] = df[col].fillna(df[col].median())

df.isnull().sum()


age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hemo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

## Model Training

In [68]:
X = df.drop('classification', axis=1)  # X is feature
Y = df['classification']               # Y is the target

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

scaler = MinMaxScaler()
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

## Training and testing of different models

## Define models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
} 
for name, model in models.items():
    model.fit(X_train, Y_train)       # Train model
    Y_pred = model.predict(X_test)    # Make predictions
    print(name, "" , model)

Logistic Regression  LogisticRegression(max_iter=1000)
Random Forest  RandomForestClassifier(random_state=42)
Gradient Boosting  GradientBoostingClassifier(random_state=42)


## Evaluate and print the result

In [69]:
for name, model in models.items():
    print(f"\n--- {name} ---")
    print(f"Accuracy: {accuracy_score(Y_test, Y_pred):.4f}")
    print("Confusion Matrix:")
    print(confusion_matrix(Y_test, Y_pred))
    print("Classification Report:")
    print(classification_report(Y_test, Y_pred))
    print("="*30)


--- Logistic Regression ---
Accuracy: 0.9875
Confusion Matrix:
[[28  0]
 [ 1 51]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98        28
           1       1.00      0.98      0.99        52

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80


--- Random Forest ---
Accuracy: 0.9875
Confusion Matrix:
[[28  0]
 [ 1 51]]
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98        28
           1       1.00      0.98      0.99        52

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.99        80
weighted avg       0.99      0.99      0.99        80


--- Gradient Boosting ---
Accuracy: 0.9875
Confusion Matrix:
[[28  0]
 [ 1 51]]
Classification Report:
              precision    recall  f